name: flutter_final_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  charts_flutter: ^0.12.0
  cloud_firestore: ^4.15.4
  easy_separator: ^1.0.1
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.3
  firebase_database: ^10.4.5
  firebase_messaging: ^14.7.15
  firebase_storage: ^11.6.5
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_application_4: ^0.0.1
  flutter_gemini: ^2.0.1
  flutter_local_notifications: ^16.3.2
  flutter_pdfview: ^1.3.2
  flutter_svg: ^2.0.9
  flutter_zoom_drawer: ^3.1.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  image_picker: ^1.0.7
  liquid_pull_to_refresh: ^3.0.1
  logger: ^2.0.2+1
  path_provider: ^2.1.2
  pie_chart: ^5.4.0
  random_string: ^2.3.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  youtube_player_flutter: ^8.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
assets:
  - assets/